" Pathogen commands
"call pathogen#runtime_append_all_bundles()
"call pathogen#infect()
"call pathogen#helptags()


" For jsflakes
filetype on
filetype plugin on


" For pyflakes
filetype plugin indent on


" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim


" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
" if has("syntax")
"  syntax on
" endif


" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif


" Setting up Vundle - the vim plugin bundler
let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing vundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let iCanHazVundle=0
endif
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
" Unite
Bundle 'Shougo/unite.vim'
" Vundle bundles
Bundle 'Syntastic' 
" erik's colorscheme
Bundle 'altercation/vim-colors-solarized' 
" So awesome, it should be illegal
Bundle 'https://github.com/tpope/vim-fugitive' 
" Misc
Bundle 'https://github.com/tpope/vim-sensible'
Bundle 'https://github.com/vim-scripts/closetag.vim'
Bundle 'https://github.com/kevinw/pyflakes-vim'
if iCanHazVundle == 0
    echo "Installing Bundles, please ignore key map error messges"
    echo ""
    :BundleInstall
endif
" Setting up Vundle end


"{{CommandT Settings
"
" Increase file buffer
" let CommandTMaxFiles=20000

"}}}


"{{{Misc Settings

" Set <Leader>t key
nnoremap t :Unite -start-insert file<cr>

" Line Numbers, turn off when using tmux with node
" set number

" Setting indents to 4 spaces
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Cursor moves to different lines
set whichwrap+=<,>,h,l,[,]

" Unite settings
call unite#filters#matcher_default#use(['matcher_fuzzy'])

"}}}
